# **LOCAL FOOD WASTAGE MANAGEMENT SYSTEM PROJECT**

# **Load Datasets**

In [2]:
import pandas as pd

providers = pd.read_csv("C:/Users/Harika challa/Innovexis/Project-2/providers_data.csv")
receivers = pd.read_csv("C:/Users/Harika challa/Innovexis/Project-2/receivers_data.csv")
food = pd.read_csv("C:/Users/Harika challa/Innovexis/Project-2/food_listings_data.csv")
claims = pd.read_csv("C:/Users/Harika challa/Innovexis/Project-2/claims_data.csv")

# **Display first few rows**

In [11]:
print(providers.head())

   Provider_ID                         Name           Type  \
0            1             Gonzales-Cochran    Supermarket
1            2  Nielsen, Johnson and Fuller  Grocery Store
2            3                 Miller-Black    Supermarket
3            4   Clark, Prince and Williams  Grocery Store
4            5               Coleman-Farley  Grocery Store

                                             Address            City  \
0  74347 Christopher Extensions\nAndreamouth, OK ...     New Jessica
1           91228 Hanson Stream\nWelchtown, OR 27136     East Sheena
2  561 Martinez Point Suite 507\nGuzmanchester, W...  Lake Jesusview
3     467 Bell Trail Suite 409\nPort Jesus, IA 61188     Mendezmouth
4  078 Matthew Creek Apt. 319\nSaraborough, MA 53978   Valentineside

                Contact
0       +1-600-220-0480
1  +1-925-283-8901x6297
2      001-517-295-2206
3      556.944.8935x401
4          193.714.6577

In [12]:
print(receivers.head())

   Receiver_ID          Name        Type               City           Contact
0            1  Donald Gomez     Shelter     Port Carlburgh     (955)922-5295
1            2  Laurie Ramos  Individual         Lewisburgh      761.042.1570
2            3  Ashley Mckee         NGO  South Randalltown  691-023-0094x856
3            4    Erika Rose         NGO   South Shaneville        8296491111
4            5   John Romero  Individual          Bakerport      067.491.0154

In [13]:
print(food.head())

   Food_ID Food_Name  Quantity Expiry_Date  Provider_ID     Provider_Type  \
0        1     Bread        43   3/17/2025          110     Grocery Store
1        2      Soup        22   3/24/2025          791     Grocery Store
2        3    Fruits        46   3/28/2025          478  Catering Service
3        4    Fruits        15   3/16/2025          930        Restaurant
4        5      Soup        14   3/19/2025          279        Restaurant

           Location       Food_Type  Meal_Type
0  South Kellyville  Non-Vegetarian  Breakfast
1        West James  Non-Vegetarian     Dinner
2       Lake Regina           Vegan  Breakfast
3         Kellytown           Vegan      Lunch
4        Garciaport           Vegan     Dinner

In [14]:
print(claims.head())

   Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0         1      164          908    Pending    3/5/2025 5:26
1         2      353          391  Cancelled  3/11/2025 10:24
2         3      626          492  Completed   3/21/2025 0:59
3         4       61          933  Cancelled    3/4/2025 9:08
4         5      345          229    Pending  3/14/2025 15:17

# **Check for Dataset Duplicate Value Count**

In [15]:
duplicate_count = providers.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [16]:
duplicate_count = receivers.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [17]:
duplicate_count = food.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [18]:
duplicate_count = claims.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

# **Checking for Missing/Null Values**

In [ ]:
# Check for missing values
print(providers.isnull().sum())

Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64

In [20]:
print(receivers.isnull().sum())

Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64

In [21]:
print(food.isnull().sum())

Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64

In [22]:
print(claims.isnull().sum())

Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64

# **Dataset Info**

In [26]:
providers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Provider_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   Address      1000 non-null   str
 4   City         1000 non-null   str
 5   Contact      1000 non-null   str
dtypes: int64(1), str(5)
memory usage: 145.6 KB

In [27]:
receivers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Receiver_ID  1000 non-null   int64
 1   Name         1000 non-null   str
 2   Type         1000 non-null   str
 3   City         1000 non-null   str
 4   Contact      1000 non-null   str
dtypes: int64(1), str(4)
memory usage: 86.1 KB

In [28]:
food.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   str
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   str
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   str
 6   Location       1000 non-null   str
 7   Food_Type      1000 non-null   str
 8   Meal_Type      1000 non-null   str
dtypes: int64(3), str(6)
memory usage: 124.2 KB

In [29]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   str
 4   Timestamp    1000 non-null   str
dtypes: int64(3), str(2)
memory usage: 61.2 KB

In [6]:
providers.columns

Index(['Provider_ID', 'Name', 'Type', 'Address', 'City', 'Contact'], dtype='str')

In [7]:
receivers.columns

Index(['Receiver_ID', 'Name', 'Type', 'City', 'Contact'], dtype='str')

In [8]:
food.columns

Index(['Food_ID', 'Food_Name', 'Quantity', 'Expiry_Date', 'Provider_ID',
       'Provider_Type', 'Location', 'Food_Type', 'Meal_Type'],
      dtype='str')

In [9]:
claims.columns

Index(['Claim_ID', 'Food_ID', 'Receiver_ID', 'Status', 'Timestamp'], dtype='str')

# **Data Cleaning**

In [20]:
#Cleaning Date Datatypes
food["Expiry_Date"] = pd.to_datetime(food["Expiry_Date"], errors="coerce")
claims["Timestamp"] = pd.to_datetime(claims["Timestamp"], errors="coerce")

In [21]:
food.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Food_ID        1000 non-null   int64
 1   Food_Name      1000 non-null   str
 2   Quantity       1000 non-null   int64
 3   Expiry_Date    1000 non-null   datetime64[us]
 4   Provider_ID    1000 non-null   int64
 5   Provider_Type  1000 non-null   str
 6   Location       1000 non-null   str
 7   Food_Type      1000 non-null   str
 8   Meal_Type      1000 non-null   str
dtypes: datetime64[us](1), int64(3), str(5)
memory usage: 115.4 KB

In [7]:
claims.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Claim_ID     1000 non-null   int64
 1   Food_ID      1000 non-null   int64
 2   Receiver_ID  1000 non-null   int64
 3   Status       1000 non-null   str
 4   Timestamp    1000 non-null   datetime64[us]
dtypes: datetime64[us](1), int64(3), str(1)
memory usage: 47.3 KB

In [13]:
#Cleaning Providers Contact details column
import pandas as pd
import re

def clean_contact(contact):
    if pd.isna(contact):
        return None
    
    contact = str(contact)
    
    # Remove extension like x123
    contact = re.sub(r"x\d+", "", contact)
    
    # Keep only digits
    contact = re.sub(r"\D", "", contact)
    
    return contact  

# Apply cleaning
providers["Contact"] = providers["Contact"].apply(clean_contact)

In [14]:
providers.head()

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,16002200480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,19252838901
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,0015172952206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,5569448935
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,1937146577

In [18]:
#Cleaning receivers Contact details column
import pandas as pd
import re

def clean_contact(contact):
    if pd.isna(contact):
        return None
    
    contact = str(contact)
    
    # Remove extension like x123
    contact = re.sub(r"x\d+", "", contact)
    
    # Keep only digits
    contact = re.sub(r"\D", "", contact)
    
    return contact 

# Apply cleaning
receivers["Contact"] = receivers["Contact"].apply(clean_contact)

In [19]:
receivers.head()

   Receiver_ID          Name        Type               City     Contact
0            1  Donald Gomez     Shelter     Port Carlburgh  9559225295
1            2  Laurie Ramos  Individual         Lewisburgh  7610421570
2            3  Ashley Mckee         NGO  South Randalltown  6910230094
3            4    Erika Rose         NGO   South Shaneville  8296491111
4            5   John Romero  Individual          Bakerport  0674910154

# **Save cleaned data**

In [22]:

# Save cleaned data
providers.to_csv("C:/Users/Harika challa/Innovexis/Project-2/clean_providers.csv", index=False)
receivers.to_csv("C:/Users/Harika challa/Innovexis/Project-2/clean_receivers.csv", index=False)
food.to_csv("C:/Users/Harika challa/Innovexis/Project-2/clean_food.csv", index=False)
claims.to_csv("C:/Users/Harika challa/Innovexis/Project-2/clean_claims.csv", index=False)