# **Project Name**    - BLOOMBERG EQUITY DATA EXTRACTION

##### **Project Type**    - Data Cleaning
##### **Contribution**    - Individual

# **Project Summary -**

Bloomberg-Style Financial Performance & CFO Analytics is a financial data analysis project focused on transforming a Bloomberg-style synthetic financial dataset covering FY2016–FY2023 into a clean, structured, and decision-ready analytical model.

The project analyzes revenue trends, profitability, operating expenses, product and channel performance, and geographic revenue to understand the key factors affecting financial performance.

Python/Pandas was used for data cleaning and validation, Excel for financial modeling, and Power BI/DAX for financial analysis and visualization. The final analysis converts raw financial data into management-oriented insights and recommendations around revenue recovery, cost pressure, and operating profitability.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

Raw financial extracts are often not immediately suitable for business analysis because they may contain inconsistent formats, text-based financial values, missing-value indicators, duplicate or subtotal records, and changes in reporting structures across financial years.

Without proper cleaning, validation, and modeling, these issues can result in incorrect financial calculations, misleading KPIs, and unreliable management insights.

Therefore, the project addresses the problem of transforming raw Bloomberg-style financial data into a reliable analytical model that can be used to evaluate revenue performance, profitability, operating expenses, business segments, and geographic performance.

#### **Define Your Business Objective?**

Build a reliable and analysis-ready financial dataset from Bloomberg-style equity data for Adidas AG (ADS GY Equity).

The Python workflow will:

1. Load raw Bloomberg-style financial data.
2. Clean financial values and labels.
3. Correct identified data-quality anomalies.
4. Remove only verified duplicate records.
5. Validate financial reconciliations.
6. Prepare analysis-ready datasets.
7. Generate a final data-quality report.

EDA and dashboard development will be performed separately in Power BI.

Evaluate revenue growth, profitability, operating-cost intensity, segment performance, and geographic trends to identify the key drivers of financial performance and areas requiring management attention.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [2]:
# Import Libraries
# ============================================================
# IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import re
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

#### File Configuration

In [3]:
# ============================================================
# FILE CONFIGURATION
# ============================================================

EXCEL_FILE = Path(
    r"C:/Users/Harika challa/Innovexis/Project-13/ADS_GY_Equity_Bloomberg_Extract_SYNTHETIC.xlsx"
)

CLEAN_DIR = Path(
    r"C:/Users/Harika challa/Innovexis/Project-13/Clean_Data"
)

CLEAN_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FISCAL_YEARS = list(range(2016, 2024))

YEAR_COLUMNS = [
    f"FY_{year}"
    for year in FISCAL_YEARS
]

print("Input file:", EXCEL_FILE)
print("Output folder:", CLEAN_DIR)
print("Fiscal years:", FISCAL_YEARS)

Input file: C:\Users\Harika challa\Innovexis\Project-13\ADS_GY_Equity_Bloomberg_Extract_SYNTHETIC.xlsx
Output folder: C:\Users\Harika challa\Innovexis\Project-13\Clean_Data
Fiscal years: [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

### Dataset Loading

In [4]:
# Load Dataset
# ============================================================
# LOAD RAW DATA
# ============================================================

excel_file = pd.ExcelFile(EXCEL_FILE)

print("Available sheets:")
print(excel_file.sheet_names)

raw_pl = pd.read_excel(
    EXCEL_FILE,
    sheet_name="ADS GY Equity",
    header=None
)

raw_segment = pd.read_excel(
    EXCEL_FILE,
    sheet_name="REV BY SEGMENT",
    header=None
)

raw_geo = pd.read_excel(
    EXCEL_FILE,
    sheet_name="REV BY GEO",
    header=None
)

raw_opex = pd.read_excel(
    EXCEL_FILE,
    sheet_name="OPEX DETAIL",
    header=None
)

print("\nRaw dataset shapes:")
print("P&L:", raw_pl.shape)
print("Revenue by Segment:", raw_segment.shape)
print("Revenue by Geography:", raw_geo.shape)
print("OPEX:", raw_opex.shape)

Available sheets:
['ADS GY Equity', 'REV BY SEGMENT', 'REV BY GEO', 'OPEX DETAIL', 'LOOKUP TABLES', 'README']

Raw dataset shapes:
P&L: (57, 10)
Revenue by Segment: (27, 10)
Revenue by Geography: (28, 10)
OPEX: (26, 10)

### Dataset First View

In [ ]:
# Dataset First Look
print("\nRaw P&L dataset preview:")
print(raw_pl.head(10))

Raw P&L dataset preview:
                                                   0    1           2  \
0                                          Bloomberg  NaN         NaN
1                  ADS GY Equity     -     ADIDAS AG  NaN         NaN
2  Income Statement   |   Standardized   |   Peri...  NaN         NaN
3  Currency: EUR        Units: Millions (except p...  NaN         NaN
4  *** SYNTHETIC SAMPLE DATA - GENERATED FOR CLAS...  NaN         NaN
5                                                NaN  NaN         NaN
6                In Millions of EUR except Per Share  NaN     FY 2016
7                                                NaN  NaN  12/31/2016
8                                                NaN  NaN         NaN
9                                            Revenue  NaN         NaN

            3           4           5           6           7           8  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN
5         NaN         NaN         NaN         NaN         NaN         NaN
6     FY 2017     FY 2018     FY 2019     FY 2020     FY 2021     FY 2022
7  12/31/2017  12/31/2018  12/31/2019  12/31/2020  12/31/2021  12/31/2022
8         NaN         NaN         NaN         NaN         NaN         NaN
9         NaN         NaN         NaN         NaN         NaN         NaN

            9
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6     FY 2023
7  12/31/2023
8         NaN
9         NaN

Raw Revenue by Segment dataset preview:
                                                   0    1         2         3  \
0  ADS GY Equity  -  Revenue Analysis (SYNTHETIC ...  NaN       NaN       NaN
1  Units: EUR mn      Source: Bloomberg segment d...  NaN       NaN       NaN
2                                                NaN  NaN       NaN       NaN
3                                            Segment  NaN      FY16      FY17
4                                                NaN  NaN       NaN       NaN
5                                BY PRODUCT CATEGORY  NaN       NaN       NaN
6                                           Footwear  NaN  10,073.0  11,712.0
7                                           Apparel   NaN   7,264.0   8,190.0
8                                        Acc. & Gear  NaN   1,146.0   1,316.0
9                                           Footwear  NaN  10,073.0  11,712.0

          4         5         6         7         8         9
0       NaN       NaN       NaN       NaN       NaN       NaN
1       NaN       NaN       NaN       NaN       NaN       NaN
2       NaN       NaN       NaN       NaN       NaN       NaN
3      FY18      FY19      FY20      FY21      FY22      FY23
4       NaN       NaN       NaN       NaN       NaN       NaN
5       NaN       NaN       NaN       NaN       NaN       NaN
6  12,272.0  13,380.0  11,629.0  12,252.0  12,831.0  12,470.0
7   8,306.0   8,865.0   7,104.0   7,772.0   8,397.0   7,757.0
8   1,337.0   1,395.0   1,111.0   1,210.0   1,283.0   1,200.0
9  12,272.0  13,380.0  11,629.0  12,252.0  12,831.0  12,470.0

Raw Revenue by Geography dataset preview:
                                                   0   1        2        3  \
0  ADS GY Equity  -  Net Revenue by Reporting Reg... NaN      NaN      NaN
1  Units: EUR mn.  Regional segmentation was rest... NaN      NaN      NaN
2                                                NaN NaN      NaN      NaN
3                                             Region NaN     2016     2017
4                                                NaN NaN      NaN      NaN
5           REPORTED SEGMENTATION - FY2016 to FY2019 NaN      NaN      NaN
6                                     Western Europe NaN  5,452.0  5,856.0
7                                      North America NaN  3,068.0  3,947.0
8                                        Grtr China  NaN  2,976.0  3,756.0
9                                       Russia / CIS NaN    721.0    700.0

         4        5     6     7     8     9
0      NaN      NaN   NaN   NaN   NaN   NaN
1      NaN      NaN   NaN   NaN   NaN   NaN
2      NaN      NaN   NaN   NaN   NaN   NaN
3     2018     2019  2020  2021  2022  2023
4      NaN      NaN   NaN   NaN   NaN   NaN
5      NaN      NaN   NaN   NaN   NaN   NaN
6  5,764.0  5,957.0     —     —     —     —
7  4,361.0  4,917.0     —     —     —     —
8  4,164.0  4,728.0     —     —     —     —
9    679.0    686.0     —     —     —     —

Raw OPEX dataset preview:
                                                   0   1        2        3  \
0  ADS GY Equity  -  Operating Expense Detail (SY... NaN      NaN      NaN
1                        Units: EUR mn unless stated NaN      NaN      NaN
2                                                NaN NaN      NaN      NaN
3                                       Expense Line NaN  FY 2016  FY 2017
4                                                NaN NaN      NaN      NaN
5                                  ABSOLUTE (EUR mn) NaN      NaN      NaN
6                        Marketing and point-of-sale NaN  2,532.0  2,843.0
7                           Distribution and selling NaN  4,029.0  4,710.0
8                         General and administration NaN    998.0  1,125.0
9                                    Sundry expenses NaN    185.0    212.0

         4        5        6        7        8        9
0      NaN      NaN      NaN      NaN      NaN      NaN
1      NaN      NaN      NaN      NaN      NaN      NaN
2      NaN      NaN      NaN      NaN      NaN      NaN
3  FY 2018  FY 2019  FY 2020  FY 2021  FY 2022  FY 2023
4      NaN      NaN      NaN      NaN      NaN      NaN
5      NaN      NaN      NaN      NaN      NaN      NaN
6  2,871.0  3,026.0  2,361.0  2,569.0  2,791.0  2,636.0
7  4,909.0  5,272.0  5,358.0  4,969.0  5,470.0  5,528.0
8  1,140.0  1,347.0  1,290.0  1,295.0  1,756.0  1,564.0
9    219.0    236.0    198.0    212.0    225.0    257.0

In [9]:
print("\nRaw Revenue by Segment dataset preview:")
print(raw_segment.head(10))

Raw Revenue by Segment dataset preview:
                                                   0    1         2         3  \
0  ADS GY Equity  -  Revenue Analysis (SYNTHETIC ...  NaN       NaN       NaN
1  Units: EUR mn      Source: Bloomberg segment d...  NaN       NaN       NaN
2                                                NaN  NaN       NaN       NaN
3                                            Segment  NaN      FY16      FY17
4                                                NaN  NaN       NaN       NaN
5                                BY PRODUCT CATEGORY  NaN       NaN       NaN
6                                           Footwear  NaN  10,073.0  11,712.0
7                                           Apparel   NaN   7,264.0   8,190.0
8                                        Acc. & Gear  NaN   1,146.0   1,316.0
9                                           Footwear  NaN  10,073.0  11,712.0

          4         5         6         7         8         9
0       NaN       NaN       NaN       NaN       NaN       NaN
1       NaN       NaN       NaN       NaN       NaN       NaN
2       NaN       NaN       NaN       NaN       NaN       NaN
3      FY18      FY19      FY20      FY21      FY22      FY23
4       NaN       NaN       NaN       NaN       NaN       NaN
5       NaN       NaN       NaN       NaN       NaN       NaN
6  12,272.0  13,380.0  11,629.0  12,252.0  12,831.0  12,470.0
7   8,306.0   8,865.0   7,104.0   7,772.0   8,397.0   7,757.0
8   1,337.0   1,395.0   1,111.0   1,210.0   1,283.0   1,200.0
9  12,272.0  13,380.0  11,629.0  12,252.0  12,831.0  12,470.0

In [10]:
print("\nRaw Revenue by Geography dataset preview:")
print(raw_geo.head(10))

Raw Revenue by Geography dataset preview:
                                                   0   1        2        3  \
0  ADS GY Equity  -  Net Revenue by Reporting Reg... NaN      NaN      NaN
1  Units: EUR mn.  Regional segmentation was rest... NaN      NaN      NaN
2                                                NaN NaN      NaN      NaN
3                                             Region NaN     2016     2017
4                                                NaN NaN      NaN      NaN
5           REPORTED SEGMENTATION - FY2016 to FY2019 NaN      NaN      NaN
6                                     Western Europe NaN  5,452.0  5,856.0
7                                      North America NaN  3,068.0  3,947.0
8                                        Grtr China  NaN  2,976.0  3,756.0
9                                       Russia / CIS NaN    721.0    700.0

         4        5     6     7     8     9
0      NaN      NaN   NaN   NaN   NaN   NaN
1      NaN      NaN   NaN   NaN   NaN   NaN
2      NaN      NaN   NaN   NaN   NaN   NaN
3     2018     2019  2020  2021  2022  2023
4      NaN      NaN   NaN   NaN   NaN   NaN
5      NaN      NaN   NaN   NaN   NaN   NaN
6  5,764.0  5,957.0     —     —     —     —
7  4,361.0  4,917.0     —     —     —     —
8  4,164.0  4,728.0     —     —     —     —
9    679.0    686.0     —     —     —     —

In [11]:
print("\nRaw OPEX dataset preview:")
print(raw_opex.head(10))

Raw OPEX dataset preview:
                                                   0   1        2        3  \
0  ADS GY Equity  -  Operating Expense Detail (SY... NaN      NaN      NaN
1                        Units: EUR mn unless stated NaN      NaN      NaN
2                                                NaN NaN      NaN      NaN
3                                       Expense Line NaN  FY 2016  FY 2017
4                                                NaN NaN      NaN      NaN
5                                  ABSOLUTE (EUR mn) NaN      NaN      NaN
6                        Marketing and point-of-sale NaN  2,532.0  2,843.0
7                           Distribution and selling NaN  4,029.0  4,710.0
8                         General and administration NaN    998.0  1,125.0
9                                    Sundry expenses NaN    185.0    212.0

         4        5        6        7        8        9
0      NaN      NaN      NaN      NaN      NaN      NaN
1      NaN      NaN      NaN      NaN      NaN      NaN
2      NaN      NaN      NaN      NaN      NaN      NaN
3  FY 2018  FY 2019  FY 2020  FY 2021  FY 2022  FY 2023
4      NaN      NaN      NaN      NaN      NaN      NaN
5      NaN      NaN      NaN      NaN      NaN      NaN
6  2,871.0  3,026.0  2,361.0  2,569.0  2,791.0  2,636.0
7  4,909.0  5,272.0  5,358.0  4,969.0  5,470.0  5,528.0
8  1,140.0  1,347.0  1,290.0  1,295.0  1,756.0  1,564.0
9    219.0    236.0    198.0    212.0    225.0    257.0

### Dataset Rows & Columns count

In [12]:
# Dataset Rows & Columns count
print("\nRaw dataset shapes:")
print("P&L:", raw_pl.shape)
print("Revenue by Segment:", raw_segment.shape)
print("Revenue by Geography:", raw_geo.shape)
print("OPEX:", raw_opex.shape)

Raw dataset shapes:
P&L: (57, 10)
Revenue by Segment: (27, 10)
Revenue by Geography: (28, 10)
OPEX: (26, 10)

### Dataset Information

In [15]:
# Dataset Info
print("\nRaw dataset info:")
raw_pl.info()

Raw dataset info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       48 non-null     object
 1   1       3 non-null      object
 2   2       35 non-null     object
 3   3       36 non-null     object
 4   4       35 non-null     object
 5   5       36 non-null     object
 6   6       36 non-null     object
 7   7       36 non-null     object
 8   8       35 non-null     object
 9   9       36 non-null     object
dtypes: object(10)
memory usage: 4.6+ KB

In [16]:
raw_segment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       21 non-null     object
 1   1       1 non-null      object
 2   2       13 non-null     object
 3   3       13 non-null     object
 4   4       13 non-null     object
 5   5       13 non-null     object
 6   6       13 non-null     object
 7   7       13 non-null     object
 8   8       13 non-null     object
 9   9       13 non-null     object
dtypes: object(10)
memory usage: 2.2+ KB

In [17]:
raw_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       22 non-null     object
 1   1       0 non-null      float64
 2   2       16 non-null     object
 3   3       16 non-null     object
 4   4       16 non-null     object
 5   5       16 non-null     object
 6   6       16 non-null     object
 7   7       16 non-null     object
 8   8       16 non-null     object
 9   9       16 non-null     object
dtypes: float64(1), object(9)
memory usage: 2.3+ KB

In [18]:
raw_opex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     object
 1   1       0 non-null      float64
 2   2       14 non-null     object
 3   3       14 non-null     object
 4   4       14 non-null     object
 5   5       14 non-null     object
 6   6       14 non-null     object
 7   7       14 non-null     object
 8   8       14 non-null     object
 9   9       14 non-null     object
dtypes: float64(1), object(9)
memory usage: 2.2+ KB

#### Data Cleaning Functions

In [19]:
# ============================================================
# DATA CLEANING FUNCTIONS
# ============================================================

def clean_label(value):
    """
    Standardize text labels and remove footnote markers.
    """

    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    value = re.sub(
        r"\(\d+\)",
        "",
        value
    )

    value = re.sub(
        r"\[\d+\]",
        "",
        value
    )

    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value.strip()


def clean_financial_value(value):
    """
    Convert Bloomberg-style financial values to numeric.
    """

    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    missing_values = {
        "",
        "-",
        "—",
        "–",
        "NM",
        "N/M",
        "N/A",
        "NA",
        "#N/A",
        "#NA",
        "NULL",
        "NONE"
    }

    if value.upper() in missing_values:
        return np.nan

    value = value.replace(",", "")
    value = value.replace(" ", "")
    value = value.replace("%", "")

    if value.startswith("(") and value.endswith(")"):
        value = "-" + value[1:-1]

    value = re.sub(
        r"[^0-9.\-]",
        "",
        value
    )

    if value in {"", "-", ".", "-."}:
        return np.nan

    try:
        return float(value)

    except ValueError:
        return np.nan


def validate_reconciliation(
    df,
    components,
    total_label,
    group_column=None,
    tolerance=0.01
):
    """
    Validate that component values reconcile to reported total.
    """

    results = []

    years = sorted(
        df["fiscal_year"].dropna().unique()
    )

    for year in years:

        year_data = df[
            df["fiscal_year"] == year
        ]

        component_data = year_data[
            year_data["item"].isin(components)
        ]

        total_data = year_data[
            year_data["item"] == total_label
        ]

        component_sum = component_data["value"].sum()

        if len(total_data) > 0:
            reported_total = total_data["value"].iloc[0]
        else:
            reported_total = np.nan

        difference = (
            component_sum - reported_total
            if pd.notna(reported_total)
            else np.nan
        )

        status = (
            "PASS"
            if pd.notna(difference)
            and abs(difference) <= tolerance
            else "REVIEW_REQUIRED"
        )

        results.append({
            "Fiscal Year": int(year),
            "Component Sum": component_sum,
            "Reported Total": reported_total,
            "Difference": difference,
            "Status": status
        })

    return pd.DataFrame(results)

#### P&L Cleaning

Extract P&L

In [20]:
# ============================================================
# P&L — EXTRACT DATA
# ============================================================

year_row = 6
data_start_row = 9

years = (
    raw_pl.iloc[
        year_row,
        2:10
    ]
    .astype(str)
    .str.extract(r"(\d{4})")[0]
    .astype(int)
    .tolist()
)

pl = raw_pl.iloc[
    data_start_row:,
    0:10
].copy()

pl.columns = [
    "line_item",
    "footnote",
    *[f"FY_{year}" for year in years]
]

pl = pl.reset_index(drop=True)

print("Extracted P&L shape:", pl.shape)
display(pl.head(15))

Extracted P&L shape: (48, 10)

,line_item,footnote,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wholesale,NaN,"11,663.0","12,943.0","12,733.0","13,191.0","10,160.0","11,148.0","12,156.0","11,142.0"
2,Retail,NaN,"5,841.0","7,172.0","8,196.0","9,480.0","8,970.0","9,428.0","9,725.0","9,706.0"
3,Other Businesses,(2),979.0,"1,103.0","986,000",969.0,714.0,658.0,630.0,579.0
4,Total Net Revenue,NaN,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
5,Revenue Growth Y/Y,NaN,NM,14.8%,3.3%,7.9%,-16.1%,7.0%,6.0%,-4.8%
6,Total Net Revenue,NaN,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Cost of Goods Sold,NaN,"(9,500.0)","(10,524.0)","(10,607.0)","(11,347.0)","(9,982.0)","(10,511.0)","(11,863.0)","(11,249.0)"
9,GROSS PROFIT,NaN,"8,983.0","10,694.0","11,308.0","12,293.0","9,862.0","10,723.0","10,648.0","10,178.0"
10,Gross Margin %,NaN,48.6%,50.4%,51.6%,52.0%,49.7%,50.5%,47.3%,47.5%
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Royalty and Commission Income,NaN,108.0,115.0,121.0,130.0,96.0,104.0,112.0,107.0
13,Other Operating Income,NaN,60.0,66.0,71.0,78.0,52.0,58.0,63.0,55.0
14,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Clean P&L Labels

In [21]:
# ============================================================
# P&L — CLEAN LABELS
# ============================================================

pl["line_item"] = pl["line_item"].apply(
    clean_label
)

pl["footnote"] = pl["footnote"].apply(
    clean_label
)

pl = pl[
    pl["line_item"].notna()
].copy()

pl = pl[
    pl["line_item"].astype(str).str.strip() != ""
].copy()

pl = pl.reset_index(drop=True)

display(pl.head(15))

,line_item,footnote,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wholesale,NaN,"11,663.0","12,943.0","12,733.0","13,191.0","10,160.0","11,148.0","12,156.0","11,142.0"
2,Retail,NaN,"5,841.0","7,172.0","8,196.0","9,480.0","8,970.0","9,428.0","9,725.0","9,706.0"
3,Other Businesses,,979.0,"1,103.0","986,000",969.0,714.0,658.0,630.0,579.0
4,Total Net Revenue,NaN,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
5,Revenue Growth Y/Y,NaN,NM,14.8%,3.3%,7.9%,-16.1%,7.0%,6.0%,-4.8%
6,Total Net Revenue,NaN,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
7,Cost of Goods Sold,NaN,"(9,500.0)","(10,524.0)","(10,607.0)","(11,347.0)","(9,982.0)","(10,511.0)","(11,863.0)","(11,249.0)"
8,GROSS PROFIT,NaN,"8,983.0","10,694.0","11,308.0","12,293.0","9,862.0","10,723.0","10,648.0","10,178.0"
9,Gross Margin %,NaN,48.6%,50.4%,51.6%,52.0%,49.7%,50.5%,47.3%,47.5%
10,Royalty and Commission Income,NaN,108.0,115.0,121.0,130.0,96.0,104.0,112.0,107.0
11,Other Operating Income,NaN,60.0,66.0,71.0,78.0,52.0,58.0,63.0,55.0
12,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Marketing and Point-of-Sale,NaN,"(2,532.0)","(2,843.0)","(2,871.0)","(3,026.0)","(2,361.0)","(2,569.0)","(2,791.0)","(2,636.0)"
14,Distribution and Selling Expense,NaN,"(4,029.0)","(4,710.0)","(4,909.0)","(5,272.0)","(5,358.0)","(4,969.0)","(5,470.0)","(5,528.0)"

Numeric Conversion

In [22]:
# ============================================================
# P&L — NUMERIC CONVERSION
# ============================================================

for column in YEAR_COLUMNS:

    pl[column] = pl[column].apply(
        clean_financial_value
    )

display(
    pl[
        ["line_item"] + YEAR_COLUMNS
    ].head(20)
)

,line_item,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wholesale,11663.0,12943.0,12733.0,13191.0,10160.0,11148.0,12156.0,11142.0
2,Retail,5841.0,7172.0,8196.0,9480.0,8970.0,9428.0,9725.0,9706.0
3,Other Businesses,979.0,1103.0,986000.0,969.0,714.0,658.0,630.0,579.0
4,Total Net Revenue,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0
5,Revenue Growth Y/Y,NaN,14.8,3.3,7.9,-16.1,7.0,6.0,-4.8
6,Total Net Revenue,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0
7,Cost of Goods Sold,-9500.0,-10524.0,-10607.0,-11347.0,-9982.0,-10511.0,-11863.0,-11249.0
8,GROSS PROFIT,8983.0,10694.0,11308.0,12293.0,9862.0,10723.0,10648.0,10178.0
9,Gross Margin %,48.6,50.4,51.6,52.0,49.7,50.5,47.3,47.5
10,Royalty and Commission Income,108.0,115.0,121.0,130.0,96.0,104.0,112.0,107.0
11,Other Operating Income,60.0,66.0,71.0,78.0,52.0,58.0,63.0,55.0
12,Other Operating Expenses,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Marketing and Point-of-Sale,-2532.0,-2843.0,-2871.0,-3026.0,-2361.0,-2569.0,-2791.0,-2636.0
14,Distribution and Selling Expense,-4029.0,-4710.0,-4909.0,-5272.0,-5358.0,-4969.0,-5470.0,-5528.0
15,General & Administration,-998.0,-1125.0,-1140.0,-1347.0,-1290.0,-1295.0,-1756.0,-1564.0
16,Sundry Expenses,-185.0,-212.0,-219.0,-236.0,-198.0,-212.0,-225.0,-257.0
17,Total Other Operating Exp.,-7744.0,-8890.0,-9139.0,-9881.0,-9207.0,-9045.0,-10242.0,-9985.0
18,Goodwill / Intangible Impairment,NaN,NaN,NaN,NaN,NaN,NaN,-194.0,NaN
19,OPERATING PROFIT (EBIT),1407.0,1985.0,2361.0,2620.0,803.0,1840.0,387.0,355.0

Metric Classification

In [23]:
# ============================================================
# P&L — METRIC CLASSIFICATION
# ============================================================

percentage_metrics = {
    "Revenue Growth Y/Y",
    "Gross Margin %",
    "Operating Margin %",
    "Net Margin %",
    "Expense / Sales",
    "Effective Tax Rate %"
}

per_share_metrics = {
    "Basic EPS",
    "Diluted EPS",
    "Dividend Per Share (DPS)"
}

share_metrics = {
    "Wtd. Avg Shares - Basic (mn)",
    "Wtd. Avg Shares - Diluted (mn)"
}


def classify_metric(label):

    if label in percentage_metrics:
        return "Percentage"

    if label in per_share_metrics:
        return "Per Share"

    if label in share_metrics:
        return "Shares"

    return "Financial Value"


pl["metric_type"] = pl[
    "line_item"
].apply(
    classify_metric
)

display(
    pl[
        ["line_item", "metric_type"]
    ]
)

                                            line_item      metric_type
0                                             Revenue  Financial Value
1                                           Wholesale  Financial Value
2                                              Retail  Financial Value
3                                    Other Businesses  Financial Value
4                                   Total Net Revenue  Financial Value
5                                  Revenue Growth Y/Y       Percentage
6                                   Total Net Revenue  Financial Value
7                                  Cost of Goods Sold  Financial Value
8                                        GROSS PROFIT  Financial Value
9                                      Gross Margin %       Percentage
10                      Royalty and Commission Income  Financial Value
11                             Other Operating Income  Financial Value
12                           Other Operating Expenses  Financial Value
13                        Marketing and Point-of-Sale  Financial Value
14                   Distribution and Selling Expense  Financial Value
15                           General & Administration  Financial Value
16                                    Sundry Expenses  Financial Value
17                         Total Other Operating Exp.  Financial Value
18                   Goodwill / Intangible Impairment  Financial Value
19                            OPERATING PROFIT (EBIT)  Financial Value
20                                 Operating Margin %       Percentage
21                                   Financial Income  Financial Value
22                                 Financial Expenses  Financial Value
23                                Income Before Taxes  Financial Value
24                                 Income Tax Expense  Financial Value
25                               Effective Tax Rate %       Percentage
26                    Net Income from Continuing Ops.  Financial Value
27                   Net Income from Disc. Operations  Financial Value
28                                 Net Income (Total)  Financial Value
29                            Less: Minority Interest  Financial Value
30                 NET INCOME ATTRIB. TO SHAREHOLDERS  Financial Value
31                                          Basic EPS        Per Share
32                                        Diluted EPS        Per Share
33                       Wtd. Avg Shares - Basic (mn)           Shares
34                     Wtd. Avg Shares - Diluted (mn)           Shares
35                           Dividend Per Share (DPS)        Per Share
36  Source: Bloomberg Standardized Financials --- ...  Financial Value
37  FY2021 reflects Reebok operations presented as...  Financial Value
38  Value shown as extracted from the terminal; co...  Financial Value
39  FY2019 onward reflects IFRS 16 lease accountin...  Financial Value
40  NM = not meaningful. #N/A N/A = field not avai...  Financial Value
41  These figures are synthetic training data and ...  Financial Value

FY2018 Anomaly Correction

In [24]:
# ============================================================
# P&L — FY2018 ANOMALY CHECK AND CORRECTION
# ============================================================

target_mask = (
    pl["line_item"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("other businesses")
)

fy2018_audit = pl.loc[
    target_mask,
    ["line_item", "FY_2018"]
].copy()

if len(fy2018_audit) == 0:

    print("Other Businesses row not found in current P&L dataset.")

else:

    fy2018_audit["raw_value_FY2018"] = (
        fy2018_audit["FY_2018"]
    )

    correction_mask = (
        pl["line_item"]
        .astype(str)
        .str.strip()
        .str.lower()
        .eq("other businesses")
        &
        pl["FY_2018"].eq(986000)
    )

    pl.loc[
        correction_mask,
        "FY_2018"
    ] = 986

    fy2018_audit["validated_value_FY2018"] = (
        pl.loc[
            fy2018_audit.index,
            "FY_2018"
        ]
    )

    fy2018_audit[
        "FY2018_data_quality_status"
    ] = np.where(
        fy2018_audit["raw_value_FY2018"].eq(986000)
        &
        fy2018_audit["validated_value_FY2018"].eq(986),
        "CORRECTED_UNIT_SCALE",
        "NO_CORRECTION_REQUIRED"
    )

display(fy2018_audit)

,line_item,FY_2018,raw_value_FY2018,validated_value_FY2018,FY2018_data_quality_status
3,Other Businesses,986000.0,986000.0,986.0,CORRECTED_UNIT_SCALE

P&L Duplicate Detection

In [25]:
# ============================================================
# P&L — DUPLICATE DETECTION
# ============================================================

duplicate_mask = pl.duplicated(
    subset=[
        "line_item",
        "footnote",
        *YEAR_COLUMNS
    ],
    keep=False
)

pl_duplicates = pl[
    duplicate_mask
].copy()

print(
    "Duplicate P&L rows found:",
    len(pl_duplicates)
)

display(pl_duplicates)

Duplicate P&L rows found: 2

,line_item,footnote,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023,metric_type
4,Total Net Revenue,NaN,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Financial Value
6,Total Net Revenue,NaN,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Financial Value

Remove Exact Duplicate P&L Rows

In [26]:
# ============================================================
# P&L — REMOVE EXACT DUPLICATES
# ============================================================

duplicate_count = pl.duplicated(
    subset=[
        "line_item",
        "footnote",
        *YEAR_COLUMNS
    ]
).sum()

pl = pl.drop_duplicates(
    subset=[
        "line_item",
        "footnote",
        *YEAR_COLUMNS
    ]
).copy()

pl = pl.reset_index(drop=True)

print(
    "Exact duplicate rows removed:",
    duplicate_count
)

print(
    "Final P&L rows:",
    len(pl)
)

Exact duplicate rows removed: 1
Final P&L rows: 41

P&L Long Format

In [27]:
# ============================================================
# P&L — CREATE ANALYSIS-READY LONG DATASET
# ============================================================

pl_long = pl.melt(
    id_vars=[
        "line_item",
        "footnote",
        "metric_type"
    ],
    value_vars=YEAR_COLUMNS,
    var_name="fiscal_year",
    value_name="value"
)

pl_long["fiscal_year"] = (
    pl_long["fiscal_year"]
    .str.replace("FY_", "")
    .astype(int)
)

pl_long["company"] = "Adidas AG"
pl_long["ticker"] = "ADS GY"
pl_long["currency"] = "EUR"
pl_long["unit"] = "Millions"

pl_long = pl_long[
    [
        "company",
        "ticker",
        "fiscal_year",
        "line_item",
        "footnote",
        "metric_type",
        "value",
        "currency",
        "unit"
    ]
]

display(pl_long.head(20))

,company,ticker,fiscal_year,line_item,footnote,metric_type,value,currency,unit
0,Adidas AG,ADS GY,2016,Revenue,NaN,Financial Value,NaN,EUR,Millions
1,Adidas AG,ADS GY,2016,Wholesale,NaN,Financial Value,11663.0,EUR,Millions
2,Adidas AG,ADS GY,2016,Retail,NaN,Financial Value,5841.0,EUR,Millions
3,Adidas AG,ADS GY,2016,Other Businesses,,Financial Value,979.0,EUR,Millions
4,Adidas AG,ADS GY,2016,Total Net Revenue,NaN,Financial Value,18483.0,EUR,Millions
5,Adidas AG,ADS GY,2016,Revenue Growth Y/Y,NaN,Percentage,NaN,EUR,Millions
6,Adidas AG,ADS GY,2016,Cost of Goods Sold,NaN,Financial Value,-9500.0,EUR,Millions
7,Adidas AG,ADS GY,2016,GROSS PROFIT,NaN,Financial Value,8983.0,EUR,Millions
8,Adidas AG,ADS GY,2016,Gross Margin %,NaN,Percentage,48.6,EUR,Millions
9,Adidas AG,ADS GY,2016,Royalty and Commission Income,NaN,Financial Value,108.0,EUR,Millions
10,Adidas AG,ADS GY,2016,Other Operating Income,NaN,Financial Value,60.0,EUR,Millions
11,Adidas AG,ADS GY,2016,Other Operating Expenses,NaN,Financial Value,NaN,EUR,Millions
12,Adidas AG,ADS GY,2016,Marketing and Point-of-Sale,NaN,Financial Value,-2532.0,EUR,Millions
13,Adidas AG,ADS GY,2016,Distribution and Selling Expense,NaN,Financial Value,-4029.0,EUR,Millions
14,Adidas AG,ADS GY,2016,General & Administration,NaN,Financial Value,-998.0,EUR,Millions
15,Adidas AG,ADS GY,2016,Sundry Expenses,NaN,Financial Value,-185.0,EUR,Millions
16,Adidas AG,ADS GY,2016,Total Other Operating Exp.,NaN,Financial Value,-7744.0,EUR,Millions
17,Adidas AG,ADS GY,2016,Goodwill / Intangible Impairment,NaN,Financial Value,NaN,EUR,Millions
18,Adidas AG,ADS GY,2016,OPERATING PROFIT (EBIT),NaN,Financial Value,1407.0,EUR,Millions
19,Adidas AG,ADS GY,2016,Operating Margin %,NaN,Percentage,7.6,EUR,Millions

Revenue Validation

In [28]:
# ============================================================
# P&L — REVENUE RECONCILIATION
# ============================================================

revenue_components = [
    "Wholesale",
    "Retail",
    "Other Businesses"
]

revenue_data = pl_long[
    pl_long["line_item"].isin(
        revenue_components + ["Total Net Revenue"]
    )
].copy()

revenue_validation = validate_reconciliation(
    revenue_data.rename(
        columns={"line_item": "item"}
    ),
    components=revenue_components,
    total_label="Total Net Revenue"
)

display(revenue_validation)

   Fiscal Year  Component Sum  Reported Total  Difference Status
0         2016        18483.0         18483.0         0.0   PASS
1         2017        21218.0         21218.0         0.0   PASS
2         2018        21915.0         21915.0         0.0   PASS
3         2019        23640.0         23640.0         0.0   PASS
4         2020        19844.0         19844.0         0.0   PASS
5         2021        21234.0         21234.0         0.0   PASS
6         2022        22511.0         22511.0         0.0   PASS
7         2023        21427.0         21427.0         0.0   PASS

Gross Profit Validation

In [30]:
# ============================================================
# P&L — GROSS PROFIT RECONCILIATION
# ============================================================

gross_profit_rows = []

for year in FISCAL_YEARS:

    revenue = pl.loc[
        pl["line_item"].eq("Total Net Revenue"),
        f"FY_{year}"
    ].iloc[0]

    cogs = pl.loc[
        pl["line_item"].eq("Cost of Goods Sold"),
        f"FY_{year}"
    ].iloc[0]

    reported_gp = pl.loc[
        pl["line_item"].eq("GROSS PROFIT"),
        f"FY_{year}"
    ].iloc[0]

    calculated_gp = revenue + cogs

    difference = calculated_gp - reported_gp

    gross_profit_rows.append({
        "Fiscal Year": year,
        "Revenue": revenue,
        "COGS": cogs,
        "Calculated Gross Profit": calculated_gp,
        "Reported Gross Profit": reported_gp,
        "Difference": difference,
        "Status": (
            "PASS"
            if abs(difference) <= 0.01
            else "REVIEW_REQUIRED"
        )
    })

gross_profit_validation = pd.DataFrame(
    gross_profit_rows
)

display(gross_profit_validation)

,Fiscal Year,Revenue,COGS,Calculated Gross Profit,Reported Gross Profit,Difference,Status
0,2016,18483.0,-9500.0,8983.0,8983.0,0.0,PASS
1,2017,21218.0,-10524.0,10694.0,10694.0,0.0,PASS
2,2018,21915.0,-10607.0,11308.0,11308.0,0.0,PASS
3,2019,23640.0,-11347.0,12293.0,12293.0,0.0,PASS
4,2020,19844.0,-9982.0,9862.0,9862.0,0.0,PASS
5,2021,21234.0,-10511.0,10723.0,10723.0,0.0,PASS
6,2022,22511.0,-11863.0,10648.0,10648.0,0.0,PASS
7,2023,21427.0,-11249.0,10178.0,10178.0,0.0,PASS

Gross Margin Validation

In [64]:
gross_margin_rows = []

for year in FISCAL_YEARS:

    revenue = pl.loc[
        pl["line_item"].eq("Total Net Revenue"),
        f"FY_{year}"
    ].iloc[0]

    gross_profit = pl.loc[
        pl["line_item"].eq("GROSS PROFIT"),
        f"FY_{year}"
    ].iloc[0]

    reported_margin = pl.loc[
        pl["line_item"].eq("Gross Margin %"),
        f"FY_{year}"
    ].iloc[0]

    calculated_margin = (gross_profit / revenue) * 100

    difference = calculated_margin - reported_margin

    status = (
        "PASS"
        if abs(difference) <= 0.1
        else "REVIEW_REQUIRED"
    )

    gross_margin_rows.append({
        "Fiscal Year": year,
        "Calculated Margin": round(calculated_margin, 3),
        "Reported Margin": round(reported_margin, 3),
        "Difference": round(difference, 3),
        "Status": status
    })

gross_margin_validation = pd.DataFrame(gross_margin_rows)

display(gross_margin_validation)

   Fiscal Year  Calculated Margin  Reported Margin  Difference Status
0         2016             48.601             48.6       0.001   PASS
1         2017             50.401             50.4       0.001   PASS
2         2018             51.599             51.6      -0.001   PASS
3         2019             52.001             52.0       0.001   PASS
4         2020             49.698             49.7      -0.002   PASS
5         2021             50.499             50.5      -0.001   PASS
6         2022             47.301             47.3       0.001   PASS
7         2023             47.501             47.5       0.001   PASS

EBIT Validation

In [34]:
# ============================================================
# P&L — EBIT VALIDATION
# ============================================================

ebit_rows = []

for year in FISCAL_YEARS:

    gp = pl.loc[
        pl["line_item"].eq("GROSS PROFIT"),
        f"FY_{year}"
    ].iloc[0]

    other_income = pl.loc[
        pl["line_item"].eq("Royalty and Commission Income"),
        f"FY_{year}"
    ].iloc[0]

    other_operating_income = pl.loc[
        pl["line_item"].eq("Other Operating Income"),
        f"FY_{year}"
    ].iloc[0]

    total_opex = pl.loc[
        pl["line_item"].eq("Total Other Operating Exp."),
        f"FY_{year}"
    ].iloc[0]

    impairment_values = pl.loc[
        pl["line_item"].eq("Goodwill / Intangible Impairment"),
        f"FY_{year}"
    ]

    impairment = (
        impairment_values.iloc[0]
        if not impairment_values.empty
        else 0
    )

    if pd.isna(impairment):
        impairment = 0

    calculated_ebit = (
        gp
        + other_income
        + other_operating_income
        + total_opex
        + impairment
    )

    reported_ebit = pl.loc[
        pl["line_item"].eq("OPERATING PROFIT (EBIT)"),
        f"FY_{year}"
    ].iloc[0]

    difference = calculated_ebit - reported_ebit

    ebit_rows.append({
        "Fiscal Year": year,
        "Calculated EBIT": calculated_ebit,
        "Reported EBIT": reported_ebit,
        "Difference": difference,
        "Status": (
            "PASS"
            if abs(difference) <= 0.01
            else "REVIEW_REQUIRED"
        )
    })

ebit_validation = pd.DataFrame(ebit_rows)

display(ebit_validation)

   Fiscal Year  Calculated EBIT  Reported EBIT  Difference Status
0         2016           1407.0         1407.0         0.0   PASS
1         2017           1985.0         1985.0         0.0   PASS
2         2018           2361.0         2361.0         0.0   PASS
3         2019           2620.0         2620.0         0.0   PASS
4         2020            803.0          803.0         0.0   PASS
5         2021           1840.0         1840.0         0.0   PASS
6         2022            387.0          387.0         0.0   PASS
7         2023            355.0          355.0         0.0   PASS

EPS Validation

In [35]:
# ============================================================
# P&L — EPS VALIDATION
# ============================================================

eps_rows = []

for year in FISCAL_YEARS:

    net_income = pl.loc[
        pl["line_item"].eq(
            "NET INCOME ATTRIB. TO SHAREHOLDERS"
        ),
        f"FY_{year}"
    ].iloc[0]

    shares = pl.loc[
        pl["line_item"].eq(
            "Wtd. Avg Shares - Basic (mn)"
        ),
        f"FY_{year}"
    ].iloc[0]

    reported_eps = pl.loc[
        pl["line_item"].eq("Basic EPS"),
        f"FY_{year}"
    ].iloc[0]

    calculated_eps = (
        net_income / shares
        if shares != 0
        else np.nan
    )

    difference = (
        calculated_eps - reported_eps
    )

    eps_rows.append({
        "Fiscal Year": year,
        "Calculated EPS": calculated_eps,
        "Reported EPS": reported_eps,
        "Difference": difference,
        "Status": (
            "PASS"
            if abs(difference) <= 0.05
            else "REVIEW_REQUIRED"
        )
    })

eps_validation = pd.DataFrame(
    eps_rows
)

display(eps_validation)

   Fiscal Year  Calculated EPS  Reported EPS  Difference Status
0         2016        4.721393          4.72    0.001393   PASS
1         2017        6.780247          6.78    0.000247   PASS
2         2018        8.450000          8.45    0.000000   PASS
3         2019        9.478794          9.48   -0.001206   PASS
4         2020        1.785898          1.79   -0.004102   PASS
5         2021        7.390194          7.39    0.000194   PASS
6         2022        0.272480          0.27    0.002480   PASS
7         2023       -0.184770         -0.18   -0.004770   PASS

## ***Revenue by Segment***

In [36]:
# ============================================================
# REVENUE BY SEGMENT — EXTRACT
# ============================================================

segment_years = YEAR_COLUMNS

product_segment = raw_segment.iloc[
    6:11,
    [0, 2, 3, 4, 5, 6, 7, 8, 9]
].copy()

product_segment.columns = [
    "segment",
    *segment_years
]

product_segment["segment_type"] = (
    "Product Category"
)


brand_segment = raw_segment.iloc[
    13:16,
    [0, 2, 3, 4, 5, 6, 7, 8, 9]
].copy()

brand_segment.columns = [
    "segment",
    *segment_years
]

brand_segment["segment_type"] = (
    "Brand"
)


distribution_segment = raw_segment.iloc[
    18:22,
    [0, 2, 3, 4, 5, 6, 7, 8, 9]
].copy()

distribution_segment.columns = [
    "segment",
    *segment_years
]

distribution_segment["segment_type"] = (
    "Distribution Channel"
)

Clean Segment Values

In [37]:
# ============================================================
# REVENUE BY SEGMENT — CLEAN VALUES
# ============================================================

segment_clean = pd.concat(
    [
        product_segment,
        brand_segment,
        distribution_segment
    ],
    ignore_index=True
)

segment_clean["segment"] = (
    segment_clean["segment"]
    .apply(clean_label)
)

for column in YEAR_COLUMNS:

    segment_clean[column] = (
        segment_clean[column]
        .apply(clean_financial_value)
    )

segment_clean = segment_clean[
    segment_clean["segment"].notna()
].copy()

display(segment_clean)

,segment,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023,segment_type
0,Footwear,10073.0,11712.0,12272.0,13380.0,11629.0,12252.0,12831.0,12470.0,Product Category
1,Apparel,7264.0,8190.0,8306.0,8865.0,7104.0,7772.0,8397.0,7757.0,Product Category
2,Acc. & Gear,1146.0,1316.0,1337.0,1395.0,1111.0,1210.0,1283.0,1200.0,Product Category
3,Footwear,10073.0,11712.0,12272.0,13380.0,11629.0,12252.0,12831.0,12470.0,Product Category
4,Total,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Product Category
5,adidas,16746.0,19457.0,20271.0,21985.0,18614.0,20045.0,22511.0,21427.0,Brand
6,Reebok,1737.0,1761.0,1644.0,1655.0,1230.0,1189.0,NaN,NaN,Brand
7,Total,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Brand
8,Wholesale,11663.0,12943.0,12733.0,13191.0,10160.0,11148.0,12156.0,11142.0,Distribution Channel
9,Retail,5841.0,7172.0,8196.0,9480.0,8970.0,9428.0,9725.0,9706.0,Distribution Channel
10,Other Businesses,979.0,1103.0,986.0,969.0,714.0,658.0,630.0,579.0,Distribution Channel
11,Total,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Distribution Channel

Detect Exact Duplicate Segment Rows

In [38]:
# ============================================================
# REVENUE BY SEGMENT — DUPLICATE CHECK
# ============================================================

segment_duplicate_mask = segment_clean.duplicated(
    subset=[
        "segment_type",
        "segment",
        *YEAR_COLUMNS
    ],
    keep=False
)

segment_duplicates = segment_clean[
    segment_duplicate_mask
].copy()

print(
    "Duplicate segment rows found:",
    len(segment_duplicates)
)

display(segment_duplicates)

Duplicate segment rows found: 2

,segment,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023,segment_type
0,Footwear,10073.0,11712.0,12272.0,13380.0,11629.0,12252.0,12831.0,12470.0,Product Category
3,Footwear,10073.0,11712.0,12272.0,13380.0,11629.0,12252.0,12831.0,12470.0,Product Category

Remove Exact Duplicate

In [39]:
# ============================================================
# REVENUE BY SEGMENT — REMOVE EXACT DUPLICATES
# ============================================================

segment_duplicate_count = segment_clean.duplicated(
    subset=[
        "segment_type",
        "segment",
        *YEAR_COLUMNS
    ]
).sum()

segment_clean = segment_clean.drop_duplicates(
    subset=[
        "segment_type",
        "segment",
        *YEAR_COLUMNS
    ]
).copy()

segment_clean.reset_index(
    drop=True,
    inplace=True
)

print(
    "Exact segment duplicates removed:",
    segment_duplicate_count
)

Exact segment duplicates removed: 1

Segment Long Format

In [40]:
# ============================================================
# REVENUE BY SEGMENT — LONG FORMAT
# ============================================================

segment_long = segment_clean.melt(
    id_vars=[
        "segment_type",
        "segment"
    ],
    value_vars=YEAR_COLUMNS,
    var_name="fiscal_year",
    value_name="revenue"
)

segment_long["fiscal_year"] = (
    segment_long["fiscal_year"]
    .str.replace("FY_", "")
    .astype(int)
)

segment_long["company"] = "Adidas AG"
segment_long["ticker"] = "ADS GY"
segment_long["currency"] = "EUR"
segment_long["unit"] = "Millions"

segment_long = segment_long[
    [
        "company",
        "ticker",
        "fiscal_year",
        "segment_type",
        "segment",
        "revenue",
        "currency",
        "unit"
    ]
]

display(segment_long.head(20))

,company,ticker,fiscal_year,segment_type,segment,revenue,currency,unit
0,Adidas AG,ADS GY,2016,Product Category,Footwear,10073.0,EUR,Millions
1,Adidas AG,ADS GY,2016,Product Category,Apparel,7264.0,EUR,Millions
2,Adidas AG,ADS GY,2016,Product Category,Acc. & Gear,1146.0,EUR,Millions
3,Adidas AG,ADS GY,2016,Product Category,Total,18483.0,EUR,Millions
4,Adidas AG,ADS GY,2016,Brand,adidas,16746.0,EUR,Millions
5,Adidas AG,ADS GY,2016,Brand,Reebok,1737.0,EUR,Millions
6,Adidas AG,ADS GY,2016,Brand,Total,18483.0,EUR,Millions
7,Adidas AG,ADS GY,2016,Distribution Channel,Wholesale,11663.0,EUR,Millions
8,Adidas AG,ADS GY,2016,Distribution Channel,Retail,5841.0,EUR,Millions
9,Adidas AG,ADS GY,2016,Distribution Channel,Other Businesses,979.0,EUR,Millions
10,Adidas AG,ADS GY,2016,Distribution Channel,Total,18483.0,EUR,Millions
11,Adidas AG,ADS GY,2017,Product Category,Footwear,11712.0,EUR,Millions
12,Adidas AG,ADS GY,2017,Product Category,Apparel,8190.0,EUR,Millions
13,Adidas AG,ADS GY,2017,Product Category,Acc. & Gear,1316.0,EUR,Millions
14,Adidas AG,ADS GY,2017,Product Category,Total,21218.0,EUR,Millions
15,Adidas AG,ADS GY,2017,Brand,adidas,19457.0,EUR,Millions
16,Adidas AG,ADS GY,2017,Brand,Reebok,1761.0,EUR,Millions
17,Adidas AG,ADS GY,2017,Brand,Total,21218.0,EUR,Millions
18,Adidas AG,ADS GY,2017,Distribution Channel,Wholesale,12943.0,EUR,Millions
19,Adidas AG,ADS GY,2017,Distribution Channel,Retail,7172.0,EUR,Millions

Segment Reconciliation

In [41]:
# ============================================================
# REVENUE BY SEGMENT — PRODUCT VALIDATION
# ============================================================

product_data = segment_long[
    segment_long["segment_type"]
    .eq("Product Category")
].rename(
    columns={
        "segment": "item",
        "revenue": "value"
    }
)

product_validation = validate_reconciliation(
    product_data,
    components=[
        "Footwear",
        "Apparel",
        "Acc. & Gear"
    ],
    total_label="Total"
)

print("Product Category Validation")
display(product_validation)

Product Category Validation

   Fiscal Year  Component Sum  Reported Total  Difference Status
0         2016        18483.0         18483.0         0.0   PASS
1         2017        21218.0         21218.0         0.0   PASS
2         2018        21915.0         21915.0         0.0   PASS
3         2019        23640.0         23640.0         0.0   PASS
4         2020        19844.0         19844.0         0.0   PASS
5         2021        21234.0         21234.0         0.0   PASS
6         2022        22511.0         22511.0         0.0   PASS
7         2023        21427.0         21427.0         0.0   PASS

In [42]:
# ============================================================
# REVENUE BY SEGMENT — BRAND VALIDATION
# ============================================================

brand_data = segment_long[
    segment_long["segment_type"]
    .eq("Brand")
].rename(
    columns={
        "segment": "item",
        "revenue": "value"
    }
)

brand_validation = validate_reconciliation(
    brand_data,
    components=[
        "adidas",
        "Reebok"
    ],
    total_label="Total"
)

print("Brand Validation")
display(brand_validation)

Brand Validation

   Fiscal Year  Component Sum  Reported Total  Difference Status
0         2016        18483.0         18483.0         0.0   PASS
1         2017        21218.0         21218.0         0.0   PASS
2         2018        21915.0         21915.0         0.0   PASS
3         2019        23640.0         23640.0         0.0   PASS
4         2020        19844.0         19844.0         0.0   PASS
5         2021        21234.0         21234.0         0.0   PASS
6         2022        22511.0         22511.0         0.0   PASS
7         2023        21427.0         21427.0         0.0   PASS

In [43]:
# ============================================================
# REVENUE BY SEGMENT — DISTRIBUTION VALIDATION
# ============================================================

distribution_data = segment_long[
    segment_long["segment_type"]
    .eq("Distribution Channel")
].rename(
    columns={
        "segment": "item",
        "revenue": "value"
    }
)

distribution_validation = validate_reconciliation(
    distribution_data,
    components=[
        "Wholesale",
        "Retail",
        "Other Businesses"
    ],
    total_label="Total"
)

print("Distribution Channel Validation")
display(distribution_validation)

Distribution Channel Validation

   Fiscal Year  Component Sum  Reported Total  Difference Status
0         2016        18483.0         18483.0         0.0   PASS
1         2017        21218.0         21218.0         0.0   PASS
2         2018        21915.0         21915.0         0.0   PASS
3         2019        23640.0         23640.0         0.0   PASS
4         2020        19844.0         19844.0         0.0   PASS
5         2021        21234.0         21234.0         0.0   PASS
6         2022        22511.0         22511.0         0.0   PASS
7         2023        21427.0         21427.0         0.0   PASS

## ***Revenue by Geography***

REVENUE BY GEOGRAPHY — INITIAL CLEANING

In [44]:
# ============================================================
# REVENUE BY GEOGRAPHY — INITIAL CLEANING
# ============================================================

geo = raw_geo.copy()

geo = geo.dropna(
    how="all"
).dropna(
    axis=1,
    how="all"
)

geo = geo.map(
    lambda x: clean_label(x)
    if isinstance(x, str)
    else x
)

print("Cleaned raw geography shape:", geo.shape)

display(geo.head(25))

Cleaned raw geography shape: (22, 9)

,0,2,3,4,5,6,7,8,9
0,ADS GY Equity - Net Revenue by Reporting Regio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Units: EUR mn. Regional segmentation was resta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Region,2016,2017,2018,2019,2020,2021,2022,2023
5,REPORTED SEGMENTATION - FY2016 to FY2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Western Europe,"5,452.0","5,856.0","5,764.0","5,957.0",—,—,—,—
7,North America,"3,068.0","3,947.0","4,361.0","4,917.0",—,—,—,—
8,Grtr China,"2,976.0","3,756.0","4,164.0","4,728.0",—,—,—,—
9,Russia / CIS,721.0,700.0,679.0,686.0,—,—,—,—
10,Latin America,"1,645.0","1,740.0","1,688.0","1,726.0",—,—,—,—
11,Other Asian Mkts,"2,421.0","2,716.0","2,761.0","2,931.0",—,—,—,—
12,Emerging Markets,"1,220.0","1,400.0","1,512.0","1,726.0",—,—,—,—
13,Other Businesses,980.0,"1,103.0",986.0,969.0,—,—,—,—
15,REPORTED SEGMENTATION - FY2020 to FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,EMEA,—,—,—,—,"7,005.0","7,432.0","7,879.0","7,585.0"
17,North America,—,—,—,—,"4,127.0","5,330.0","5,921.0","5,142.0"
18,Greater China,—,—,—,—,"4,346.0","4,247.0","3,534.0","3,257.0"
19,Asia-Pacific,—,—,—,—,"2,342.0","2,060.0","2,656.0","2,807.0"
20,Latin America,—,—,—,—,"1,310.0","1,507.0","1,891.0","2,057.0"
21,Other Businesses,—,—,—,—,714.0,658.0,630.0,579.0
23,TOTAL NET REVENUE,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
26,Use the region mapping table on the LOOKUP TAB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Detect Geography Year Row

In [45]:
# ============================================================
# REVENUE BY GEOGRAPHY — FIND YEAR ROW
# ============================================================

geo_year_row = None

for i in range(
    min(20, len(geo))
):

    row_text = " ".join(
        geo.iloc[i]
        .astype(str)
        .tolist()
    )

    if all(
        str(year) in row_text
        for year in [2016, 2017, 2018]
    ):

        geo_year_row = i
        break

print(
    "Geography year row:",
    geo_year_row
)

Geography year row: 2

Create Geography Table

In [46]:
# ============================================================
# REVENUE BY GEOGRAPHY — CREATE CLEAN TABLE
# ============================================================

if geo_year_row is None:

    raise ValueError(
        "Geography year row could not be detected."
    )

geo_columns = []

for i, value in enumerate(
    geo.iloc[geo_year_row]
):

    if pd.isna(value):

        geo_columns.append(
            f"column_{i}"
        )

    else:

        year_match = re.search(
            r"(\d{4})",
            str(value)
        )

        if year_match:

            geo_columns.append(
                f"FY_{year_match.group(1)}"
            )

        else:

            geo_columns.append(
                clean_label(value)
            )

geo.columns = geo_columns

geo = geo.iloc[
    geo_year_row + 1:
].copy()

geo = geo.dropna(
    how="all"
)

geo = geo.reset_index(
    drop=True
)

display(geo.head(25))

,Region,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,REPORTED SEGMENTATION - FY2016 to FY2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Western Europe,"5,452.0","5,856.0","5,764.0","5,957.0",—,—,—,—
2,North America,"3,068.0","3,947.0","4,361.0","4,917.0",—,—,—,—
3,Grtr China,"2,976.0","3,756.0","4,164.0","4,728.0",—,—,—,—
4,Russia / CIS,721.0,700.0,679.0,686.0,—,—,—,—
5,Latin America,"1,645.0","1,740.0","1,688.0","1,726.0",—,—,—,—
6,Other Asian Mkts,"2,421.0","2,716.0","2,761.0","2,931.0",—,—,—,—
7,Emerging Markets,"1,220.0","1,400.0","1,512.0","1,726.0",—,—,—,—
8,Other Businesses,980.0,"1,103.0",986.0,969.0,—,—,—,—
9,REPORTED SEGMENTATION - FY2020 to FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,EMEA,—,—,—,—,"7,005.0","7,432.0","7,879.0","7,585.0"
11,North America,—,—,—,—,"4,127.0","5,330.0","5,921.0","5,142.0"
12,Greater China,—,—,—,—,"4,346.0","4,247.0","3,534.0","3,257.0"
13,Asia-Pacific,—,—,—,—,"2,342.0","2,060.0","2,656.0","2,807.0"
14,Latin America,—,—,—,—,"1,310.0","1,507.0","1,891.0","2,057.0"
15,Other Businesses,—,—,—,—,714.0,658.0,630.0,579.0
16,TOTAL NET REVENUE,"18,483.0","21,218.0","21,915.0","23,640.0","19,844.0","21,234.0","22,511.0","21,427.0"
17,Use the region mapping table on the LOOKUP TAB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Standardize Geography Columns

In [47]:
# ============================================================
# REVENUE BY GEOGRAPHY — STANDARDIZE COLUMNS
# ============================================================

geo.columns = [
    clean_label(column)
    for column in geo.columns
]

geo_label_column = geo.columns[0]

for column in geo.columns[1:]:

    if str(column).startswith("FY_"):

        geo[column] = geo[column].apply(
            clean_financial_value
        )

geo = geo[
    geo[geo_label_column].notna()
].copy()

geo = geo[
    geo[geo_label_column].astype(str).str.strip() != ""
].copy()

geo = geo.reset_index(
    drop=True
)

print("Geography columns:")
print(geo.columns.tolist())

display(geo.head(25))

Geography columns:
['Region', 'FY_2016', 'FY_2017', 'FY_2018', 'FY_2019', 'FY_2020', 'FY_2021', 'FY_2022', 'FY_2023']

,Region,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,REPORTED SEGMENTATION - FY2016 to FY2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Western Europe,5452.0,5856.0,5764.0,5957.0,NaN,NaN,NaN,NaN
2,North America,3068.0,3947.0,4361.0,4917.0,NaN,NaN,NaN,NaN
3,Grtr China,2976.0,3756.0,4164.0,4728.0,NaN,NaN,NaN,NaN
4,Russia / CIS,721.0,700.0,679.0,686.0,NaN,NaN,NaN,NaN
5,Latin America,1645.0,1740.0,1688.0,1726.0,NaN,NaN,NaN,NaN
6,Other Asian Mkts,2421.0,2716.0,2761.0,2931.0,NaN,NaN,NaN,NaN
7,Emerging Markets,1220.0,1400.0,1512.0,1726.0,NaN,NaN,NaN,NaN
8,Other Businesses,980.0,1103.0,986.0,969.0,NaN,NaN,NaN,NaN
9,REPORTED SEGMENTATION - FY2020 to FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,EMEA,NaN,NaN,NaN,NaN,7005.0,7432.0,7879.0,7585.0
11,North America,NaN,NaN,NaN,NaN,4127.0,5330.0,5921.0,5142.0
12,Greater China,NaN,NaN,NaN,NaN,4346.0,4247.0,3534.0,3257.0
13,Asia-Pacific,NaN,NaN,NaN,NaN,2342.0,2060.0,2656.0,2807.0
14,Latin America,NaN,NaN,NaN,NaN,1310.0,1507.0,1891.0,2057.0
15,Other Businesses,NaN,NaN,NaN,NaN,714.0,658.0,630.0,579.0
16,TOTAL NET REVENUE,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0
17,Use the region mapping table on the LOOKUP TAB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Geography Region Mapping

In [48]:
# ============================================================
# REVENUE BY GEOGRAPHY — REGION MAPPING
# ============================================================

def map_region(value):

    if pd.isna(value):
        return np.nan

    text = str(value).strip().lower()

    region_map = {

        "europe": "Europe",
        "north america": "North America",
        "asia": "Asia",
        "latin america": "Latin America",
        "emea": "EMEA",
        "greater china": "Greater China",
        "north america": "North America",
        "asia pacific": "Asia Pacific"
    }

    for key, region in region_map.items():

        if key in text:
            return region

    return "Other"


geo["region"] = geo[
    geo_label_column
].apply(map_region)

geo = geo.rename(
    columns={
        geo_label_column: "geography"
    }
)

display(geo.head(25))

,geography,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023,region
0,REPORTED SEGMENTATION - FY2016 to FY2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
1,Western Europe,5452.0,5856.0,5764.0,5957.0,NaN,NaN,NaN,NaN,Europe
2,North America,3068.0,3947.0,4361.0,4917.0,NaN,NaN,NaN,NaN,North America
3,Grtr China,2976.0,3756.0,4164.0,4728.0,NaN,NaN,NaN,NaN,Other
4,Russia / CIS,721.0,700.0,679.0,686.0,NaN,NaN,NaN,NaN,Other
5,Latin America,1645.0,1740.0,1688.0,1726.0,NaN,NaN,NaN,NaN,Latin America
6,Other Asian Mkts,2421.0,2716.0,2761.0,2931.0,NaN,NaN,NaN,NaN,Asia
7,Emerging Markets,1220.0,1400.0,1512.0,1726.0,NaN,NaN,NaN,NaN,Other
8,Other Businesses,980.0,1103.0,986.0,969.0,NaN,NaN,NaN,NaN,Other
9,REPORTED SEGMENTATION - FY2020 to FY2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
10,EMEA,NaN,NaN,NaN,NaN,7005.0,7432.0,7879.0,7585.0,EMEA
11,North America,NaN,NaN,NaN,NaN,4127.0,5330.0,5921.0,5142.0,North America
12,Greater China,NaN,NaN,NaN,NaN,4346.0,4247.0,3534.0,3257.0,Greater China
13,Asia-Pacific,NaN,NaN,NaN,NaN,2342.0,2060.0,2656.0,2807.0,Asia
14,Latin America,NaN,NaN,NaN,NaN,1310.0,1507.0,1891.0,2057.0,Latin America
15,Other Businesses,NaN,NaN,NaN,NaN,714.0,658.0,630.0,579.0,Other
16,TOTAL NET REVENUE,18483.0,21218.0,21915.0,23640.0,19844.0,21234.0,22511.0,21427.0,Other
17,Use the region mapping table on the LOOKUP TAB...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other
18,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other

Geography Long Format

In [49]:
# ============================================================
# REVENUE BY GEOGRAPHY — LONG FORMAT
# ============================================================

geo_year_columns = [
    column
    for column in geo.columns
    if str(column).startswith("FY_")
]

geo_long = geo.melt(
    id_vars=[
        "geography",
        "region"
    ],
    value_vars=geo_year_columns,
    var_name="fiscal_year",
    value_name="revenue"
)

geo_long["fiscal_year"] = (
    geo_long["fiscal_year"]
    .str.replace("FY_", "")
    .astype(int)
)

geo_long["company"] = "Adidas AG"
geo_long["ticker"] = "ADS GY"
geo_long["currency"] = "EUR"
geo_long["unit"] = "Millions"

geo_long = geo_long[
    [
        "company",
        "ticker",
        "fiscal_year",
        "geography",
        "region",
        "revenue",
        "currency",
        "unit"
    ]
]

display(geo_long.head(25))

,company,ticker,fiscal_year,geography,region,revenue,currency,unit
0,Adidas AG,ADS GY,2016,REPORTED SEGMENTATION - FY2016 to FY2019,Other,NaN,EUR,Millions
1,Adidas AG,ADS GY,2016,Western Europe,Europe,5452.0,EUR,Millions
2,Adidas AG,ADS GY,2016,North America,North America,3068.0,EUR,Millions
3,Adidas AG,ADS GY,2016,Grtr China,Other,2976.0,EUR,Millions
4,Adidas AG,ADS GY,2016,Russia / CIS,Other,721.0,EUR,Millions
5,Adidas AG,ADS GY,2016,Latin America,Latin America,1645.0,EUR,Millions
6,Adidas AG,ADS GY,2016,Other Asian Mkts,Asia,2421.0,EUR,Millions
7,Adidas AG,ADS GY,2016,Emerging Markets,Other,1220.0,EUR,Millions
8,Adidas AG,ADS GY,2016,Other Businesses,Other,980.0,EUR,Millions
9,Adidas AG,ADS GY,2016,REPORTED SEGMENTATION - FY2020 to FY2023,Other,NaN,EUR,Millions
10,Adidas AG,ADS GY,2016,EMEA,EMEA,NaN,EUR,Millions
11,Adidas AG,ADS GY,2016,North America,North America,NaN,EUR,Millions
12,Adidas AG,ADS GY,2016,Greater China,Greater China,NaN,EUR,Millions
13,Adidas AG,ADS GY,2016,Asia-Pacific,Asia,NaN,EUR,Millions
14,Adidas AG,ADS GY,2016,Latin America,Latin America,NaN,EUR,Millions
15,Adidas AG,ADS GY,2016,Other Businesses,Other,NaN,EUR,Millions
16,Adidas AG,ADS GY,2016,TOTAL NET REVENUE,Other,18483.0,EUR,Millions
17,Adidas AG,ADS GY,2016,Use the region mapping table on the LOOKUP TAB...,Other,NaN,EUR,Millions
18,Adidas AG,ADS GY,2016,SYNTHETIC SAMPLE DATA - classroom use only.,Other,NaN,EUR,Millions
19,Adidas AG,ADS GY,2017,REPORTED SEGMENTATION - FY2016 to FY2019,Other,NaN,EUR,Millions
20,Adidas AG,ADS GY,2017,Western Europe,Europe,5856.0,EUR,Millions
21,Adidas AG,ADS GY,2017,North America,North America,3947.0,EUR,Millions
22,Adidas AG,ADS GY,2017,Grtr China,Other,3756.0,EUR,Millions
23,Adidas AG,ADS GY,2017,Russia / CIS,Other,700.0,EUR,Millions
24,Adidas AG,ADS GY,2017,Latin America,Latin America,1740.0,EUR,Millions

## ***OPEX Detail***

Clean Raw OPEX

In [50]:
# ============================================================
# OPEX DETAIL — INITIAL CLEANING
# ============================================================

opex = raw_opex.copy()

opex = opex.dropna(
    how="all"
).dropna(
    axis=1,
    how="all"
)

opex = opex.map(
    lambda x: clean_label(x)
    if isinstance(x, str)
    else x
)

print(
    "Cleaned OPEX shape:",
    opex.shape
)

display(opex.head(25))

Cleaned OPEX shape: (20, 9)

,0,2,3,4,5,6,7,8,9
0,ADS GY Equity - Operating Expense Detail (SYNT...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Units: EUR mn unless stated,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Expense Line,FY 2016,FY 2017,FY 2018,FY 2019,FY 2020,FY 2021,FY 2022,FY 2023
5,ABSOLUTE (EUR mn),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Marketing and point-of-sale,"2,532.0","2,843.0","2,871.0","3,026.0","2,361.0","2,569.0","2,791.0","2,636.0"
7,Distribution and selling,"4,029.0","4,710.0","4,909.0","5,272.0","5,358.0","4,969.0","5,470.0","5,528.0"
8,General and administration,998.0,"1,125.0","1,140.0","1,347.0","1,290.0","1,295.0","1,756.0","1,564.0"
9,Sundry expenses,185.0,212.0,219.0,236.0,198.0,212.0,225.0,257.0
10,Goodwill / intangible impairment,—,—,—,—,—,—,194.0,—
11,Total operating expenses,"7,744.0","8,890.0","9,139.0","9,881.0","9,207.0","9,045.0","10,436.0","9,985.0"
13,AS % OF NET SALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Marketing and point-of-sale,13.7%,13.4%,13.1%,12.8%,11.9%,12.1%,12.4%,12.3%
15,Distribution and selling,21.8%,22.2%,22.4%,22.3%,27.0%,23.4%,24.3%,25.8%
16,General and administration,5.4%,5.3%,5.2%,5.7%,6.5%,6.1%,7.8%,7.3%
17,Sundry expenses,1.0%,1.0%,1.0%,1.0%,1.0%,1.0%,1.0%,1.2%
18,Total operating expenses,41.9%,41.9%,41.7%,41.8%,46.4%,42.6%,46.4%,46.6%
20,OTHER OPERATING METRICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"Employees (FTE, year-end)","60,617","56,888","57,016","59,533","62,285","61,401","59,258","57,069"
22,Revenue per employee (EUR '000),304.9,373.0,384.4,397.1,318.6,345.8,379.9,375.5
25,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Detect OPEX Year Row

In [51]:
# ============================================================
# OPEX DETAIL — FIND YEAR ROW
# ============================================================

opex_year_row = None

for i in range(
    min(20, len(opex))
):

    row_text = " ".join(
        opex.iloc[i]
        .astype(str)
        .tolist()
    )

    if all(
        str(year) in row_text
        for year in [2016, 2017, 2018]
    ):

        opex_year_row = i
        break

print(
    "OPEX year row:",
    opex_year_row
)

OPEX year row: 2

Create OPEX Table

In [52]:
# ============================================================
# OPEX DETAIL — CREATE CLEAN TABLE
# ============================================================

if opex_year_row is None:

    raise ValueError(
        "OPEX year row could not be detected."
    )

opex_columns = []

for i, value in enumerate(
    opex.iloc[opex_year_row]
):

    if pd.isna(value):

        opex_columns.append(
            f"column_{i}"
        )

    else:

        year_match = re.search(
            r"(\d{4})",
            str(value)
        )

        if year_match:

            opex_columns.append(
                f"FY_{year_match.group(1)}"
            )

        else:

            opex_columns.append(
                clean_label(value)
            )

opex.columns = opex_columns

opex = opex.iloc[
    opex_year_row + 1:
].copy()

opex = opex.dropna(
    how="all"
)

opex = opex.reset_index(
    drop=True
)

display(opex.head(25))

,Expense Line,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,ABSOLUTE (EUR mn),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Marketing and point-of-sale,"2,532.0","2,843.0","2,871.0","3,026.0","2,361.0","2,569.0","2,791.0","2,636.0"
2,Distribution and selling,"4,029.0","4,710.0","4,909.0","5,272.0","5,358.0","4,969.0","5,470.0","5,528.0"
3,General and administration,998.0,"1,125.0","1,140.0","1,347.0","1,290.0","1,295.0","1,756.0","1,564.0"
4,Sundry expenses,185.0,212.0,219.0,236.0,198.0,212.0,225.0,257.0
5,Goodwill / intangible impairment,—,—,—,—,—,—,194.0,—
6,Total operating expenses,"7,744.0","8,890.0","9,139.0","9,881.0","9,207.0","9,045.0","10,436.0","9,985.0"
7,AS % OF NET SALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Marketing and point-of-sale,13.7%,13.4%,13.1%,12.8%,11.9%,12.1%,12.4%,12.3%
9,Distribution and selling,21.8%,22.2%,22.4%,22.3%,27.0%,23.4%,24.3%,25.8%
10,General and administration,5.4%,5.3%,5.2%,5.7%,6.5%,6.1%,7.8%,7.3%
11,Sundry expenses,1.0%,1.0%,1.0%,1.0%,1.0%,1.0%,1.0%,1.2%
12,Total operating expenses,41.9%,41.9%,41.7%,41.8%,46.4%,42.6%,46.4%,46.6%
13,OTHER OPERATING METRICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Employees (FTE, year-end)","60,617","56,888","57,016","59,533","62,285","61,401","59,258","57,069"
15,Revenue per employee (EUR '000),304.9,373.0,384.4,397.1,318.6,345.8,379.9,375.5
16,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Numeric Conversion

In [53]:
# ============================================================
# OPEX DETAIL — NUMERIC CONVERSION
# ============================================================

opex.columns = [
    clean_label(column)
    for column in opex.columns
]

opex_label_column = opex.columns[0]

opex_year_columns = [
    column
    for column in opex.columns
    if str(column).startswith("FY_")
]

for column in opex_year_columns:

    opex[column] = opex[column].apply(
        clean_financial_value
    )

opex = opex[
    opex[opex_label_column].notna()
].copy()

opex = opex[
    opex[opex_label_column].astype(str).str.strip() != ""
].copy()

opex = opex.rename(
    columns={
        opex_label_column: "expense_item"
    }
)

display(opex.head(25))

,expense_item,FY_2016,FY_2017,FY_2018,FY_2019,FY_2020,FY_2021,FY_2022,FY_2023
0,ABSOLUTE (EUR mn),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Marketing and point-of-sale,2532.0,2843.0,2871.0,3026.0,2361.0,2569.0,2791.0,2636.0
2,Distribution and selling,4029.0,4710.0,4909.0,5272.0,5358.0,4969.0,5470.0,5528.0
3,General and administration,998.0,1125.0,1140.0,1347.0,1290.0,1295.0,1756.0,1564.0
4,Sundry expenses,185.0,212.0,219.0,236.0,198.0,212.0,225.0,257.0
5,Goodwill / intangible impairment,NaN,NaN,NaN,NaN,NaN,NaN,194.0,NaN
6,Total operating expenses,7744.0,8890.0,9139.0,9881.0,9207.0,9045.0,10436.0,9985.0
7,AS % OF NET SALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Marketing and point-of-sale,13.7,13.4,13.1,12.8,11.9,12.1,12.4,12.3
9,Distribution and selling,21.8,22.2,22.4,22.3,27.0,23.4,24.3,25.8
10,General and administration,5.4,5.3,5.2,5.7,6.5,6.1,7.8,7.3
11,Sundry expenses,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.2
12,Total operating expenses,41.9,41.9,41.7,41.8,46.4,42.6,46.4,46.6
13,OTHER OPERATING METRICS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"Employees (FTE, year-end)",60617.0,56888.0,57016.0,59533.0,62285.0,61401.0,59258.0,57069.0
15,Revenue per employee (EUR '000),304.9,373.0,384.4,397.1,318.6,345.8,379.9,375.5
16,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

OPEX Long Format

In [54]:
# ============================================================
# OPEX DETAIL — LONG FORMAT
# ============================================================

opex_long = opex.melt(
    id_vars=[
        "expense_item"
    ],
    value_vars=opex_year_columns,
    var_name="fiscal_year",
    value_name="expense"
)

opex_long["fiscal_year"] = (
    opex_long["fiscal_year"]
    .str.replace("FY_", "")
    .astype(int)
)

opex_long["company"] = "Adidas AG"
opex_long["ticker"] = "ADS GY"
opex_long["currency"] = "EUR"
opex_long["unit"] = "Millions"

opex_long = opex_long[
    [
        "company",
        "ticker",
        "fiscal_year",
        "expense_item",
        "expense",
        "currency",
        "unit"
    ]
]

display(opex_long.head(25))

,company,ticker,fiscal_year,expense_item,expense,currency,unit
0,Adidas AG,ADS GY,2016,ABSOLUTE (EUR mn),NaN,EUR,Millions
1,Adidas AG,ADS GY,2016,Marketing and point-of-sale,2532.0,EUR,Millions
2,Adidas AG,ADS GY,2016,Distribution and selling,4029.0,EUR,Millions
3,Adidas AG,ADS GY,2016,General and administration,998.0,EUR,Millions
4,Adidas AG,ADS GY,2016,Sundry expenses,185.0,EUR,Millions
5,Adidas AG,ADS GY,2016,Goodwill / intangible impairment,NaN,EUR,Millions
6,Adidas AG,ADS GY,2016,Total operating expenses,7744.0,EUR,Millions
7,Adidas AG,ADS GY,2016,AS % OF NET SALES,NaN,EUR,Millions
8,Adidas AG,ADS GY,2016,Marketing and point-of-sale,13.7,EUR,Millions
9,Adidas AG,ADS GY,2016,Distribution and selling,21.8,EUR,Millions
10,Adidas AG,ADS GY,2016,General and administration,5.4,EUR,Millions
11,Adidas AG,ADS GY,2016,Sundry expenses,1.0,EUR,Millions
12,Adidas AG,ADS GY,2016,Total operating expenses,41.9,EUR,Millions
13,Adidas AG,ADS GY,2016,OTHER OPERATING METRICS,NaN,EUR,Millions
14,Adidas AG,ADS GY,2016,"Employees (FTE, year-end)",60617.0,EUR,Millions
15,Adidas AG,ADS GY,2016,Revenue per employee (EUR '000),304.9,EUR,Millions
16,Adidas AG,ADS GY,2016,SYNTHETIC SAMPLE DATA - classroom use only.,NaN,EUR,Millions
17,Adidas AG,ADS GY,2017,ABSOLUTE (EUR mn),NaN,EUR,Millions
18,Adidas AG,ADS GY,2017,Marketing and point-of-sale,2843.0,EUR,Millions
19,Adidas AG,ADS GY,2017,Distribution and selling,4710.0,EUR,Millions
20,Adidas AG,ADS GY,2017,General and administration,1125.0,EUR,Millions
21,Adidas AG,ADS GY,2017,Sundry expenses,212.0,EUR,Millions
22,Adidas AG,ADS GY,2017,Goodwill / intangible impairment,NaN,EUR,Millions
23,Adidas AG,ADS GY,2017,Total operating expenses,8890.0,EUR,Millions
24,Adidas AG,ADS GY,2017,AS % OF NET SALES,NaN,EUR,Millions

OPEX Validation

In [71]:
opex_validation_rows = []

component_items = [
    "Marketing and point-of-sale",
    "Distribution and selling",
    "General and administration",
    "Sundry expenses",
    "Goodwill / intangible impairment"
]

for year in FISCAL_YEARS:

    year_data = opex_long[
        opex_long["fiscal_year"].eq(year)
    ].copy()

    component_data = year_data[
        year_data["expense_item"].isin(component_items)
        & (year_data["expense"] > 100)
    ]

    total_data = year_data[
        year_data["expense_item"].eq("Total operating expenses")
        & (year_data["expense"] > 100)
    ]

    component_sum = component_data["expense"].sum()

    reported_total = (
        total_data["expense"].iloc[0]
        if len(total_data) > 0
        else np.nan
    )

    difference = component_sum - reported_total

    status = (
        "PASS"
        if pd.notna(difference) and abs(difference) <= 0.01
        else "REVIEW_REQUIRED"
    )

    opex_validation_rows.append({
        "Fiscal Year": year,
        "Component Sum": round(component_sum, 2),
        "Reported Total": round(reported_total, 2)
        if pd.notna(reported_total) else np.nan,
        "Difference": round(difference, 2)
        if pd.notna(difference) else np.nan,
        "Status": status
    })

opex_validation = pd.DataFrame(opex_validation_rows)

display(opex_validation)

   Fiscal Year  Component Sum  Reported Total  Difference Status
0         2016         7744.0          7744.0         0.0   PASS
1         2017         8890.0          8890.0         0.0   PASS
2         2018         9139.0          9139.0         0.0   PASS
3         2019         9881.0          9881.0         0.0   PASS
4         2020         9207.0          9207.0         0.0   PASS
5         2021         9045.0          9045.0         0.0   PASS
6         2022        10436.0         10436.0         0.0   PASS
7         2023         9985.0          9985.0         0.0   PASS

Suspicious Values

In [72]:
# ============================================================
# FINAL DATA QUALITY — SUSPICIOUS VALUES
# ============================================================

suspicious_pl = pl_long[
    pl_long["value"].abs() > 100000
].copy()

suspicious_segment = segment_long[
    segment_long["revenue"].abs() > 100000
].copy()

suspicious_geo = geo_long[
    geo_long["revenue"].abs() > 100000
].copy()

suspicious_opex = opex_long[
    opex_long["expense"].abs() > 100000
].copy()

print("Suspicious P&L values:")
display(suspicious_pl)

print("Suspicious Segment values:")
display(suspicious_segment)

print("Suspicious Geography values:")
display(suspicious_geo)

print("Suspicious OPEX values:")
display(suspicious_opex)

Suspicious P&L values:

Empty DataFrame
Columns: [company, ticker, fiscal_year, line_item, footnote, metric_type, value, currency, unit]
Index: []

Suspicious Segment values:

Empty DataFrame
Columns: [company, ticker, fiscal_year, segment_type, segment, revenue, currency, unit]
Index: []

Suspicious Geography values:

Empty DataFrame
Columns: [company, ticker, fiscal_year, geography, region, revenue, currency, unit]
Index: []

Suspicious OPEX values:

Empty DataFrame
Columns: [company, ticker, fiscal_year, expense_item, expense, currency, unit]
Index: []

Validation Summary

In [73]:
# ============================================================
# FINAL DATA QUALITY — VALIDATION SUMMARY
# ============================================================

validation_summary = pd.DataFrame({

    "Validation": [
        "Revenue Reconciliation",
        "Gross Profit Reconciliation",
        "Gross Margin Validation",
        "EBIT Validation",
        "EPS Validation",
        "Product Category Reconciliation",
        "Brand Reconciliation",
        "Distribution Channel Reconciliation",
        "OPEX Reconciliation"
    ],

    "Passed": [
        (revenue_validation["Status"] == "PASS").all(),
        (gross_profit_validation["Status"] == "PASS").all(),
        (gross_margin_validation["Status"] == "PASS").all(),
        (ebit_validation["Status"] == "PASS").all(),
        (eps_validation["Status"] == "PASS").all(),
        (product_validation["Status"] == "PASS").all(),
        (brand_validation["Status"] == "PASS").all(),
        (distribution_validation["Status"] == "PASS").all(),
        (opex_validation["Status"] == "PASS").all()
    ]
})

validation_summary["Status"] = np.where(
    validation_summary["Passed"],
    "PASS",
    "REVIEW_REQUIRED"
)

display(validation_summary)

                            Validation  Passed Status
0               Revenue Reconciliation    True   PASS
1          Gross Profit Reconciliation    True   PASS
2              Gross Margin Validation    True   PASS
3                      EBIT Validation    True   PASS
4                       EPS Validation    True   PASS
5      Product Category Reconciliation    True   PASS
6                 Brand Reconciliation    True   PASS
7  Distribution Channel Reconciliation    True   PASS
8                  OPEX Reconciliation    True   PASS

## ***Final Dataset Summary***

In [74]:
# ============================================================
# FINAL DATA QUALITY — DATASET SUMMARY
# ============================================================

dataset_summary = pd.DataFrame({

    "Dataset": [
        "P&L",
        "Revenue by Segment",
        "Revenue by Geography",
        "OPEX Detail"
    ],

    "Rows": [
        len(pl_long),
        len(segment_long),
        len(geo_long),
        len(opex_long)
    ],

    "Columns": [
        len(pl_long.columns),
        len(segment_long.columns),
        len(geo_long.columns),
        len(opex_long.columns)
    ],

    "Missing Values": [
        pl_long["value"].isna().sum(),
        segment_long["revenue"].isna().sum(),
        geo_long["revenue"].isna().sum(),
        opex_long["expense"].isna().sum()
    ]
})

display(dataset_summary)

                Dataset  Rows  Columns  Missing Values
0                   P&L   328        9              79
1    Revenue by Segment    88        8               2
2  Revenue by Geography   152        8              88
3           OPEX Detail   136        7              39

## ***Export Final Clean Datasets***

In [79]:
# ============================================================
# EXPORT FINAL CLEAN DATASETS
# ============================================================

pl_long.to_csv(
    CLEAN_DIR / "ADS_GY_PL_Cleaned.csv",
    index=False
)

segment_long.to_csv(
    CLEAN_DIR / "ADS_GY_Segment_Cleaned.csv",
    index=False
)

geo_long.to_csv(
    CLEAN_DIR / "ADS_GY_Geography_Cleaned.csv",
    index=False
)

opex_long.to_csv(
    CLEAN_DIR / "ADS_GY_OPEX_Cleaned.csv",
    index=False
)

revenue_validation.to_csv(
    CLEAN_DIR / "Revenue_Validation.csv",
    index=False
)

gross_profit_validation.to_csv(
    CLEAN_DIR / "Gross_Profit_Validation.csv",
    index=False
)

gross_margin_validation.to_csv(
    CLEAN_DIR / "Gross_Margin_Validation.csv",
    index=False
)

ebit_validation.to_csv(
    CLEAN_DIR / "EBIT_Validation.csv",
    index=False
)

eps_validation.to_csv(
    CLEAN_DIR / "EPS_Validation.csv",
    index=False
)

product_validation.to_csv(
    CLEAN_DIR / "Product_Category_Validation.csv",
    index=False
)

brand_validation.to_csv(
    CLEAN_DIR / "Brand_Validation.csv",
    index=False
)

distribution_validation.to_csv(
    CLEAN_DIR / "Distribution_Validation.csv",
    index=False
)

opex_validation.to_csv(
    CLEAN_DIR / "OPEX_Validation.csv",
    index=False
)

validation_summary.to_csv(
    CLEAN_DIR / "Validation_Summary.csv",
    index=False
)

dataset_summary.to_csv(
    CLEAN_DIR / "Dataset_Summary.csv",
    index=False
)

## ***Final Data Quality Report***

In [80]:
# ============================================================
# FINAL DATA QUALITY REPORT
# ============================================================

# Calculate missing-value counts safely
pl_missing = pl_long.isna().sum().sum()
segment_missing = segment_long.isna().sum().sum()
geo_missing = geo_long.isna().sum().sum()
opex_missing = opex_long.isna().sum().sum()

quality_report = pd.DataFrame({

    "Metric": [
        "P&L Rows",
        "P&L Missing Values",
        "P&L Duplicate Rows Removed",
        "P&L Suspicious Values",
        "Segment Rows",
        "Segment Missing Values",
        "Segment Duplicate Rows Removed",
        "Segment Suspicious Values",
        "Geography Rows",
        "Geography Missing Values",
        "Geography Suspicious Values",
        "OPEX Rows",
        "OPEX Missing Values",
        "OPEX Suspicious Values",
        "FY2018 Anomaly"
    ],

    "Value": [
        len(pl_long),
        pl_missing,
        duplicate_count,
        len(suspicious_pl),
        len(segment_long),
        segment_missing,
        segment_duplicate_count,
        len(suspicious_segment),
        len(geo_long),
        geo_missing,
        len(suspicious_geo),
        len(opex_long),
        opex_missing,
        len(suspicious_opex),
        "986000 → 986"
    ]
})

display(quality_report)

quality_report.to_csv(
    CLEAN_DIR / "Data_Quality_Report.csv",
    index=False
)

                            Metric         Value
0                         P&L Rows           328
1               P&L Missing Values           383
2       P&L Duplicate Rows Removed             1
3            P&L Suspicious Values             0
4                     Segment Rows            88
5           Segment Missing Values             2
6   Segment Duplicate Rows Removed             1
7        Segment Suspicious Values             0
8                   Geography Rows           152
9         Geography Missing Values            88
10     Geography Suspicious Values             0
11                       OPEX Rows           136
12             OPEX Missing Values            39
13          OPEX Suspicious Values             0
14                  FY2018 Anomaly  986000 → 986

## ***Final Completion Check***

In [81]:
# ============================================================
# FINAL COMPLETION CHECK
# ============================================================

print("=" * 70)
print("BLOOMBERG EQUITY DATA EXTRACTION")
print("DATA CLEANING PIPELINE COMPLETED")
print("=" * 70)

print("\nFinal datasets:")

print(
    "P&L:",
    pl_long.shape
)

print(
    "Revenue by Segment:",
    segment_long.shape
)

print(
    "Revenue by Geography:",
    geo_long.shape
)

print(
    "OPEX:",
    opex_long.shape
)

print("\nValidation status:")
display(validation_summary)

print("\nOutput files:")

for file in sorted(
    CLEAN_DIR.glob("*.csv")
):

    print(file.name)

print("\nCleaning stage completed.")

======================================================================
BLOOMBERG EQUITY DATA EXTRACTION
DATA CLEANING PIPELINE COMPLETED
======================================================================

Final datasets:
P&L: (328, 9)
Revenue by Segment: (88, 8)
Revenue by Geography: (152, 8)
OPEX: (136, 7)

Validation status:

                            Validation  Passed Status
0               Revenue Reconciliation    True   PASS
1          Gross Profit Reconciliation    True   PASS
2              Gross Margin Validation    True   PASS
3                      EBIT Validation    True   PASS
4                       EPS Validation    True   PASS
5      Product Category Reconciliation    True   PASS
6                 Brand Reconciliation    True   PASS
7  Distribution Channel Reconciliation    True   PASS
8                  OPEX Reconciliation    True   PASS

Output files:
ADS_GY_Geography_Cleaned.csv
ADS_GY_OPEX_Cleaned.csv
ADS_GY_PL_Cleaned.csv
ADS_GY_Segment_Cleaned.csv
Brand_Validation.csv
Data_Quality_Report.csv
Dataset_Summary.csv
Distribution_Validation.csv
EBIT_Validation.csv
EPS_Validation.csv
Gross_Margin_Validation.csv
Gross_Profit_Validation.csv
OPEX_Validation.csv
Product_Category_Validation.csv
Revenue_Validation.csv
Validation_Summary.csv

Cleaning stage completed.

### What did you know about your dataset?

## ***2. Understanding Your Variables***

In [ ]:
# Dataset Columns

In [ ]:
# Dataset Describe

### Variables Description

Answer Here

### Check Unique Values for each variable.

In [ ]:
# Check Unique Values for each variable.

## 3. ***Data Wrangling***

### Data Wrangling Code

In [ ]:
# Write your code to make your dataset analysis ready.

### What all manipulations have you done and insights you found?

Answer Here.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

Answer Here.

# **Conclusion**

Write the conclusion here.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***